### ISSUE TITLE
Run script means you need to depend on Carmel..

### ISSUE THREAD

**Issue by TiMBuS** [miyagawa/cpanmetadb-perl#6]
In your `run` script you use `carmel exec starman` inside a `carmel exec start_server`. This results in the following error:
`Can't locate Carmel/Runner.pm in @INC`
`@INC` appears to contain all of the carmel directories, do you need to run a second carmel?

Either removing the second 'carmel exec' or adding Carmel(::Runner) to the cpanfile should fix this.

**Comment by miyagawa** [comment]
No you need a second carmel exec. You're supposed to install carmel outside
the cpanfile installation.

**Comment by TiMBuS** [comment]
I have installed Carmel to my perl's "global" location, but Carmel::Runner cannot be found after the script invokes the second carmel. It seems to be because my @INC is missing some locations.

```
$ cpanm Carmel::Runner
Carmel::Runner is up to date. (undef)

$ perldoc -lm Carmel::Runner
/home/jfunnell/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/Carmel/Runner.pm

$ ./run
start_server (pid:7066) starting now...
starting new worker 7070
Can't locate Carmel/Runner.pm in @INC (you may need to install the Carmel::Runner module) 
(@INC contains: Carmel::Runtime::FastINC=HASH(0x13954e8) 
[...] 
/home/jfunnell/perl5/perlbrew/perls/perl-5.24.0/lib/5.24.0/x86_64-linux
/home/jfunnell/perl5/perlbrew/perls/perl-5.24.0/lib/5.24.0 . )
```

Note there is no site_perl in the @INC. There are a few `Carmel::Runtime::SiteINC=HASH(0x1331738)` thingys in there though. Is that the problem?

**Comment by TiMBuS** [comment]
Annoyingly, `carmel rollout` fixes it.. Hrmm.

**Comment by TiMBuS** [comment]
Looks like this is a Carmel issue (sorry!)

SiteINC only allows two modules:
```perl
        {
            allows => {
                'Carmel/Preload.pm' => 1,
                'Module/Runtime.pm' => 1
            },
            path => "/home/jfunnell/perl5/perlbrew/perls/perl-5.24.0/lib/site_perl/5.24.0/x86_64-linux"
        }
```
Modifying it to allow Carmel/Runner.pm in Carmel/Runtime.pm will fix it:
```perl
my %allows = map { $_ => 1 } qw( Carmel/Preload.pm Carmel/Runner.pm Module/Runtime.pm );
```

Might be a recent-ish change to Carmel, or maybe you're using a 'rolled out' carmel install on your cpanmetadb host which is why you haven't seen the issue.

**Comment by miyagawa** [comment]
Yes I use rollout on production. Can you file the issue against the Carmel
repo? Thanks.

**Comment by TiMBuS** [comment]
Done :)
