### ISSUE TITLE
PGObject::Util::DBAdmin not included in the index 9h after upload

### ISSUE THREAD

**Issue by ehuelsmann** [miyagawa/cpanmetadb-perl#8]
Hi,

It's included in the history response (https://cpanmetadb.plackperl.org/v1.0/history/PGObject::Util::DBAdmin), but not in the "latest package" response (https://cpanmetadb.plackperl.org/v1.0/package/PGObject::Util::DBAdmin).

It's been 9 hours since I uploaded it and it's been indexed and available on metacpan for hours. It's not that I'm impatient, but I think there's a bug/problem here. Also, if I'm doing something wrong, please explain so I can fix on my end.

Regards, Erik.

**Comment by miyagawa** [comment]
The issue is from the upstream metacpan:

```
✗ curl -s https://cpan.metacpan.org/modules/02packages.details.txt.gz | gzcat | grep PGObject::Util::DBAdmin 
PGObject::Util::DBAdmin        0.130001  E/EH/EHUELS/PGObject-Util-DBAdmin-0.130.1.tar.gz
```

looks like the index is up-to-date on http version though.

**Comment by ehuelsmann** [comment]
Thanks for the feedback. I'll check and report with metacpan team.
